In [16]:
print('hello world')

hello world


In [17]:
1+1


2

In [18]:
import pandas

In [19]:
mylist=[1, 2, 3, 4]

In [20]:
dir(mylist) # 查看 method (OOP 特性)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [21]:
mylist.insert(2, "TWO")
mylist

[1, 2, 'TWO', 3, 4]

In [22]:
mylist.append([1]) # 將 list 加入 list 中
mylist

[1, 2, 'TWO', 3, 4, [1]]

In [23]:
mylist.extend([1]) # 將 B list ( [1] )裡的元素拿出，加入至原 list

In [24]:
mylist 

[1, 2, 'TWO', 3, 4, [1], 1]

In [25]:
mylist2 = [1, 2, 3]
mylist3 = [4, 5, 6]

In [27]:
mylist2 + mylist3 # cant support martix calculation!

[1, 2, 3, 4, 5, 6]

## use numpy array to do matrix  calculation

In [31]:
import numpy as np

array2 = np.array(mylist2)
array3 = np.array(mylist3) 

array2 + array3

array([5, 7, 9])

### futhermore, matrix

In [34]:
mat = np.array([ [2, 3], [1, 4] ])
mat

array([[2, 3],
       [1, 4]])

In [39]:
mat2 = np.array([ [5, 18, 15], [5, 19, 23] ])

In [36]:
np.diag(mat) # print the diagonal element

array([2, 4])

In [46]:
mat.T # get the transpose matrix

array([[2, 1],
       [3, 4]])

In [37]:
mat @ np.diag(mat) # martix multiplication

array([16, 18])

In [40]:
mat @ mat2

array([[ 25,  93,  99],
       [ 25,  94, 107]])

In [42]:
np.dot(mat, mat2) # same as @ operator

array([[ 25,  93,  99],
       [ 25,  94, 107]])

In [41]:
mat2 @ mat

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [43]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [45]:
mat @ np.eye(2) # same as mat

array([[2., 3.],
       [1., 4.]])

### Inverse of matrix

In [47]:
from numpy.linalg import inv # linalg stands for linear algebra
inv(mat)

array([[ 0.8, -0.6],
       [-0.2,  0.4]])

In [48]:
mat @ inv(mat)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [49]:
inv(mat) @ mat

array([[1., 0.],
       [0., 1.]])

### linear space

In [51]:
np.linspace(0, 10, 4) # get 4 evenly distributed number from 0 to 10

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## pandas

In [53]:
import pandas as pd

d = {'a' : 1, 'b' : 2, 'c' : 3}
ser = pd.Series(d, index=['a', 'b', 'c']) 

In [54]:
ser

a    1
b    2
c    3
dtype: int64

In [56]:
ser.shape

(3,)

In [58]:
a = ser.to_numpy().reshape(1, 3) # convert series to numpy (bc (3, ), we want (1, 3))
a

array([[1, 2, 3]], dtype=int64)

In [59]:
a.shape

(1, 3)